apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: udagram-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: udagram-world.com
    http:
      paths:
      - path: /
        backend:
          serviceName: udagram-frontend
          servicePort: 8100
      - path: /api/v0/feed/
        backend:
          serviceName: udagram-feed-api
          servicePort: 8080
      - path: /api/v0/users/
        backend:
          serviceName: udagram-user-api
          servicePort: 8080